baseURL = "https://johnnybilotta.com/"
title = "Johnny Bilotta | Digital Product Designer"
author = "Johnny Bilotta"
copyright = "2025"
theme = "strange-signal"
googleAnalytics = 'G-W1NNMCGNMG'

[params]
	colorScheme = "night"
	DateFormat = "2 Jan 2025"
	description = "Digital Product Designer + Developer + Technophile"
	sidebarFreeText = "Hi! My name is Johnny. I design digital products and build things."
	featuredImageDefault = "img/featured-image-default.jpg"

[menu]
[[menu.main]]
	identifier = 'home'
	name = 'Home'
	url = '/'
	weight = -110
	
[build]
  [build.buildStats]
    enable = true
  [[build.cachebusters]]
    source = 'assets/notwatching/hugo_stats\.json'
    target = 'css'
  [[build.cachebusters]]
    source = '(postcss|tailwind)\.config\.js'
    target = 'css'
[module]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    disableWatch = true
    source = 'hugo_stats.json'
    target = 'assets/notwatching/hugo_stats.json'
  [module.hugoVersion]
		extended = true
		max = ''
		min = ''

[deployment]
order = [".jpg$", ".png$"]

[[deployment.targets]]
name = "aws-s3"
URL = "s3://johnnybilotta.com?region=us-east-1"
cloudFrontDistributionID = "E73KGFHAO4YCS"