baseURL = "https://johnnybilotta.com"
title = "Johnny Bilotta | Digital Product Designer"
author = "Johnny Bilotta"
copyright = "2021"
theme = "strange-signal"
googleAnalytics = 'G-W1NNMCGNMG'

[params]
	colorScheme = "night"
	DateFormat = "2 Jan 2006"
	description = "Digital Product Designer + Developer + Technophile"
	sidebarFreeText = "Hi! My name is Johnny. I design digital products and code things."
	featuredImageDefault = "img/featured-image-default.jpg"

[menu]
[[menu.main]]
	identifier = 'home'
	name = 'Home'
	url = '/'
	weight = -110

[module]
	[module.hugoVersion]
		extended = true
		max = ''
		min = ''

[deployment]
order = [".jpg$", ".png$"]

[[deployment.targets]]
name = "aws-s3"
URL = "s3://johnnybilotta.com?region=us-east-1"